
POST http://localhost:8080/api/empleados
Content-Type: application/json

{
  "nombre": "Juancito Perez Vintage",
  "email": "juanceto01@vaxler.com",
  "legajo": 1001
}

GET http://localhost:8080/api/empleados